spring:
  application:
    name: discodeit
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    default-consumes-media-type: multipart/form-data

discodeit:
  storage:
    type: local
    local:
      root-path: ./data/uploads

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    description: 실습 디스코드 프로젝트입니다!
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}